# Use an official lightweight Python image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Install system dependencies required for TensorFlow and Google Cloud Storage
RUN apt-get update && apt-get install -y \
    gcc \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir \
    flask \
    tensorflow-cpu \
    numpy \
    google-cloud-storage \
    firebase-admin \
    google-cloud-pubsub \
    protobuf


# Expose the port your Flask app runs on
EXPOSE 8080

# Define the command to run your app
CMD ["python", "app.py"]
